[workspace]
authors = ["Daniel Esteban Palma Igor <daniel.palma.i@ug.uchile.cl>"]
channels = ["conda-forge", "bioconda"]
name = "wf-heatmap"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
nextflow = ">=25.10.2,<26"
